Better CSS support
tubearchivist/tubearchivist pull request #583
Opened 2023-11-04 19:11 UTC by extome9000

This PR removes hardcoded CSS stylesheets and allows for more stylesheets to be added. CSS files are scanned in `/app/static/css` (`style.css` is removed since it's the root stylesheet) and can be picked from the settings where the color scheme option used to be.

I have included 2 example stylesheets, `midnight.css` and `matrix.css`, to show how different styles could look.

Feedback is appreciated.

2023-11-08 15:36 UTC, bbilly1 requested changes

2023-11-08 15:36 UTC, bbilly1 commented on tubearchivist/home/src/frontend/forms.py
>      CHOICES = [
You can simplify that with something like:
```python
class UserSettingsForm(forms.Form):
    """user configurations values"""

    STYLESHEET_CHOICES = [("", "-- change stylesheet --")]
    STYLESHEET_CHOICES.extend(
        [
            (stylesheet, os.path.splitext(stylesheet)[0].title())
            for stylesheet in get_stylesheets()
        ]
    )

    stylesheet = forms.ChoiceField(
        widget=forms.Select, choices=STYLESHEET_CHOICES, required=False
    )
    page_size = forms.IntegerField(required=False)
```
This also is more explicit what is a field and what is an additional form attribute.

2023-11-08 15:36 UTC, bbilly1 commented on tubearchivist/home/src/ta/helper.py
> +def check_stylesheet(stylesheet: str):
You already implement the `get_stylesheets` functionality above, you can use that, something like this:
```python
def check_stylesheet(stylesheet: str):
    """Check if a stylesheet exists. Return dark.css as a fallback"""
    if stylesheet in get_stylesheets():
        return stylesheet

    return "dark.css"
```

2023-11-08 15:40 UTC, bbilly1 commented
Very cool, works great on some channels:
![2023-11-08_22-36-34-screenshot](https://github.com/tubearchivist/tubearchivist/assets/35427372/6da3d142-972f-479b-90ce-5cd914da5f5d)

Also midnight is quite nice too!
![2023-11-08_22-37-35-screenshot](https://github.com/tubearchivist/tubearchivist/assets/35427372/6ce354df-e3f3-4e7d-a35c-f9ecca8c1db9)

I added two small comments with suggestions.

Great addition! Do you also want to make a PR against the docs? Add some instructions? Ask people to add their own addition.

2023-11-08 22:25 UTC, extome9000 commented
I'll add a page for CSS files on the docs repository for how to make and add stylesheets. I've also committed your suggested changes.

2023-11-09 01:34 UTC, bbilly1 approved these changes

2023-11-09 02:32 UTC, bbilly1 commented
Very well done. Thanks a lot for your contribution. :-)

2023-11-09 02:33 UTC, merged